name: ESP32 CI Build with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.2.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build the application
      - name: Build
        run: |
          cd esp32_h2
          bash /opt/esp/entrypoint.sh
          /opt/esp/idf/tools/idf.py build

      - name: Install OTA Dependencies
        run: |
          pip install zigpy-cli zigpy
          wget https://raw.githubusercontent.com/espressif/esp-zigbee-sdk/refs/heads/main/tools/image_builder_tool/image_builder_tool.py

      - name: Create OTA
        run: |
          mkdir ota
          cp esp32_h2/build/hass_sensor.bin ota/hass_sensor.bin
          cd ota
          python image_builder_tool.py --create hass_sensor.ota --manuf-id 0x0 --image-type 0x0 --version 0x2 --tag-file hass_sensor.bin
          zigpy ota generate-index --ota-url-root="https://hass.uwpx.org/local/ota" *.bin > ota.json
          cat ota.json

      - name: "Upload OTA artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: ota-data
          path: ./ota

